name: CI
on: [push, pull_request, merge_group]
jobs:
  nix_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v31
      - name: Check Nix parsing
        run: |
          find . -name "*.nix" -exec nix-instantiate --parse --quiet {} >/dev/null +
      - name: Run flake checks
        run: |
          nix flake check -L
